language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
scripts:
  - npm test
  - npm build
after_success:
  - ./scripts/deploy.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
